const phonemeData = {
  p: { exampleWord: 'pen', pronunciationGuidance: 'Try to release a puff of air from your lips without making any vibration.' },
  b: { exampleWord: 'bed', pronunciationGuidance: 'Close your lips completely and then release them abruptly while making a vibration.' },
  t: { exampleWord: 'tea', pronunciationGuidance: 'Place the tip of your tongue against the ridge behind your upper teeth and then release it quickly with a puff of air.' },
  d: { exampleWord: 'day', pronunciationGuidance: 'Place the tip of your tongue against the ridge behind your upper teeth and then release it quickly with a vibration.' },
  k: { exampleWord: 'key', pronunciationGuidance: 'Raise the back of your tongue towards the soft palate and then release it quickly with a puff of air.' },
  'ɡ': { exampleWord: 'go', pronunciationGuidance: 'Raise the back of your tongue towards the soft palate and then release it quickly with a vibration.' },
  'tʃ': { exampleWord: 'church', pronunciationGuidance: 'Place the tip of your tongue against the ridge behind your upper teeth and then curl the sides of your tongue up towards the hard palate.' },
  'dʒ': { exampleWord: 'judge', pronunciationGuidance: 'Place the tip of your tongue against the ridge behind your upper teeth and then curl the sides of your tongue up towards the hard palate while making a vibration.' },
  f: { exampleWord: 'fat', pronunciationGuidance: 'Place your lower teeth against your upper lip and then blow air through the gap between your teeth.' },
  v: { exampleWord: 'van', pronunciationGuidance: 'Place your lower teeth against your upper lip and then make a vibration while blowing air through the gap between your teeth.' },
  θ: { exampleWord: 'thin', pronunciationGuidance: 'Place the tip of your tongue between your upper teeth and then push air through the gap between your tongue and teeth.' },
  ð: { exampleWord: 'this', pronunciationGuidance: 'Place the tip of your tongue between your upper teeth and then make a vibration while pushing air through the gap between your tongue and teeth.' },
  s: { exampleWord: 'sat', pronunciationGuidance: 'Place the tip of your tongue behind your upper teeth and then push air through the groove on the sides of your tongue.' },
  z: { exampleWord: 'zoo', pronunciationGuidance: 'Place the tip of your tongue behind your upper teeth and then make a vibration while pushing air through the groove on the sides of your tongue.' },
  'ʃ': { exampleWord: 'ship', pronunciationGuidance: 'Curl the front of your tongue up towards the hard palate and then push air through the narrow channel between your tongue and the hard palate.' },
  'ʒ': { exampleWord: 'vision', pronunciationGuidance: 'Curl the front of your tongue up towards the hard palate and then make a vibration while pushing air through the narrow channel between your tongue and the hard palate.' },
  h: { exampleWord: 'hat', pronunciationGuidance: 'Push air through the constricted space at the back of your throat.' },
  m: { exampleWord: 'man', pronunciationGuidance: 'Close your lips completely and then try to hum.' },
  n: { exampleWord: 'net', pronunciationGuidance: 'Place the tip of your tongue against the ridge behind your upper teeth and then allow air to flow through your nose.' },
  ŋ: { exampleWord: 'sing', pronunciationGuidance: 'Raise the back of your tongue towards the soft palate and then allow air to flow through your nose.' },
  l: { exampleWord: 'lip', pronunciationGuidance: 'Place the tip of your tongue against the ridge behind your upper teeth and then allow air to flow over the sides of your tongue.' },
  r: { exampleWord: 'run', pronunciationGuidance: 'Curl the tip of your tongue up towards the ridge behind your upper teeth and then vibrate it.' },
  j: { exampleWord: 'yet', pronunciationGuidance: 'Place the back of your tongue against the soft palate and then raise the front of your tongue towards the hard palate.' },
  w: { exampleWord: 'wet', pronunciationGuidance: 'Round your lips and push air through them while making a vibration.' },
  'ɪ': { exampleWord: 'kit', pronunciationGuidance: 'Spread your lips and stretch your tongue forward.' },
  'e': { exampleWord: 'dress', pronunciationGuidance: 'Spread your lips and stretch your tongue slightly forward.' },
  'æ': { exampleWord: 'trap', pronunciationGuidance: 'Spread your lips and flatten your tongue.' },
  'ɒ': { exampleWord: 'lot', pronunciationGuidance: 'Round your lips and relax your tongue.' },
  'ʌ': { exampleWord: 'strut', pronunciationGuidance: 'Round your lips and depress the middle of your tongue.' },
  'ʊ': { exampleWord: 'foot', pronunciationGuidance: 'Round your lips and push your tongue back.' },
  'iː': { exampleWord: 'fleece', pronunciationGuidance: 'Spread your lips and stretch your tongue forward as much as possible.' },
  'eɪ': { exampleWord: 'face', pronunciationGuidance: 'Spread your lips and stretch your tongue forward, then quickly move it back.' },
  'aɪ': { exampleWord: 'price', pronunciationGuidance: 'Spread your lips and stretch your tongue forward, then quickly move it to the position for the vowel in "cat".' },
  'ɔɪ': { exampleWord: 'choice', pronunciationGuidance: 'Round your lips and stretch your tongue forward, then quickly move it to the position for the vowel in "boy".' },
  'uː': { exampleWord: 'goose', pronunciationGuidance: 'Round your lips and push your tongue back as much.' },
};

export default phonemeData;
